#!/usr/bin/env bash

owm_setup_ensure_config() {
	[[ -f "$OWM_CONFIG_PATH" ]] && return 0

	local config_dir="$(dirname "$OWM_CONFIG_PATH")"
	mkdir -p "$config_dir"

	if hyprctl monitors -j >/dev/null 2>&1; then
		local monitors="$(hyprctl monitors -j)"
		local primary="$(echo "$monitors" | jq -r 'sort_by(.x, .id) | .[0].name // empty')"
		local secondary="$(echo "$monitors" | jq -r 'sort_by(.x, .id) | .[1].name // .[0].name // empty')"

		if [[ -n "$primary" ]]; then
			jq --arg p "$primary" --arg s "$secondary" \
				'.primary_monitor=$p | .secondary_monitor=$s' \
				"$OWM_ROOT/config/paired.json" > "$OWM_CONFIG_PATH"
			echo "Auto-detected monitors: $primary (primary), $secondary (secondary)"
			return 0
		fi
	fi

	cp "$OWM_ROOT/config/paired.json" "$OWM_CONFIG_PATH"
	echo "Created default config at $OWM_CONFIG_PATH - edit monitor names"
}

owm_setup_add_source_line() {
	local target_file="$1"
	local source_line="$2"

	[[ -f "$target_file" ]] || return 1
	grep -qF "$source_line" "$target_file" 2>/dev/null && return 0

	cat >> "$target_file" <<EOF

# BEGIN OMARCHY_WORKSPACE_MANAGER
$source_line
# END OMARCHY_WORKSPACE_MANAGER
EOF
}

owm_setup_install() {
	local base_dir="${1:-$HOME/.config/omarchy-workspace-manager}"
	local bin_path="${2:-omarchy-workspace-manager}"

	owm_setup_ensure_config

	mkdir -p "$base_dir"
	sed "s|__OWM_BIN__|$bin_path|g" "$OWM_ROOT/config/hypr-bindings.conf" > "$base_dir/bindings.conf"
	sed "s|__OWM_BIN__|$bin_path|g" "$OWM_ROOT/config/hypr-autostart.conf" > "$base_dir/autostart.conf"
	owm_setup_generate_workspace_rules > "$base_dir/workspace-rules.conf"

	# Add source lines to personal config files (Omarchy style)
	owm_setup_add_source_line "$HOME/.config/hypr/bindings.conf" "source = $base_dir/bindings.conf"
	owm_setup_add_source_line "$HOME/.config/hypr/autostart.conf" "source = $base_dir/autostart.conf"

	# Add workspace rules to hyprland.conf
	local hypr_conf="$HOME/.config/hypr/hyprland.conf"
	owm_setup_add_source_line "$hypr_conf" "source = $base_dir/workspace-rules.conf"

	echo "Configured omarchy-workspace-manager"
	hyprctl reload 2>/dev/null || true
}

owm_setup_generate_workspace_rules() {
	local primary=$(jq -r '.primary_monitor // empty' "$OWM_CONFIG_PATH")
	local secondary=$(jq -r '.secondary_monitor // empty' "$OWM_CONFIG_PATH")
	local offset=$(jq -r '.paired_offset // 10' "$OWM_CONFIG_PATH")

	echo "# Generated by Omarchy Workspace Manager"
	for ((i = 1; i <= offset; i++)); do
		if ((i == 1)); then
			echo "workspace = 1, monitor:$primary, persistent:true, default:true"
		else
			echo "workspace = $i, monitor:$primary, persistent:true"
		fi
	done
	for ((i = 1; i <= offset; i++)); do
		if ((i == 1)); then
			echo "workspace = $((1 + offset)), monitor:$secondary, persistent:true, default:true"
		else
			echo "workspace = $((i + offset)), monitor:$secondary, persistent:true"
		fi
	done
}

owm_setup_migrate_windows() {
	[[ -f "$OWM_CONFIG_PATH" ]] || return 0

	local offset=$(jq -r '.paired_offset // 10' "$OWM_CONFIG_PATH")
	local clients=$(hyprctl clients -j 2>/dev/null) || return 0

	# Move windows from secondary workspaces to their paired primary workspace
	echo "$clients" | jq -r --argjson offset "$offset" '
		.[] | select(.workspace.id > $offset and .workspace.id <= ($offset * 2)) |
		"\(.address) \(.workspace.id)"
	' | while read -r addr ws; do
		local target=$((ws - offset))
		hyprctl dispatch movetoworkspacesilent "$target,address:$addr" 2>/dev/null
	done

	echo "Migrated windows to primary workspaces"
}

owm_setup_uninstall() {
	local base_dir="${1:-$HOME/.config/omarchy-workspace-manager}"

	owm_setup_migrate_windows

	# Remove source refs (BEGIN/END blocks) from config files
	for conf in "$HOME/.config/hypr/bindings.conf" "$HOME/.config/hypr/autostart.conf" "$HOME/.config/hypr/hyprland.conf"; do
		[[ -f "$conf" ]] || continue
		sed -i '/BEGIN OMARCHY_WORKSPACE_MANAGER/,/END OMARCHY_WORKSPACE_MANAGER/d' "$conf" 2>/dev/null || true
	done

	rm -f "$base_dir/bindings.conf" "$base_dir/autostart.conf" "$base_dir/workspace-rules.conf"
	rmdir "$base_dir" 2>/dev/null || true
	echo "Removed omarchy-workspace-manager config"
	hyprctl reload 2>/dev/null || true
}
